### PR TITLE
Changed the API URL and some of the code logic to support the new api…

### PR DESCRIPTION
**Pull request by caioblima**
PR references Issue #86 

I changed the api url and need to make some changes on the code to work properly.

I want to point ou this from github URL:

"GitHub identifies contributors by author email address. This endpoint groups contribution counts by GitHub user, which includes all associated email addresses. To improve performance, only the first 500 author email addresses in the repository link to GitHub users. The rest will appear as anonymous contributors without associated GitHub user information."

### CODE REVIEW

**Comment by rowhitswami** [comment]
@caioblima well done!! :+1: 
Can you provide link to your work?

**Comment by caioblima** [comment]
@rowhitswami In "Can you provide link to your work?" - You mean if i can put my work on an heroku like app?

**Comment by rowhitswami** [comment]
@caioblima  no just host your repository on GitHub-Pages. Here's the guide to follow 
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

After saving you'll get a link and that's where your website is hosted

**Comment by caioblima** [comment]
@rowhitswami Here is the page - https://caioblima.github.io/hacktoberfest18-ft/

**Comment by rowhitswami** [comment]
@caioblima well done! :smiley: 
Thanks for your support. :heart:

**Comment by Ishaan28malik** [comment]
@rowhitswami can i also work on this ?

**Pull request merged**
